version: '3'


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - wordpress
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    init: true


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3036:3036
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_LOWER_CASE_TABLE_NAMES=1
    networks:
      - wordpress
    volumes:
      - mariadb:/var/lib/mysql/
    init: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWOR=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    init: true


networks:
  wordpress:
    driver: bridge

volumes :
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/aelaoufi/Desktop/volumes/wordpress
      o: bind 
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/aelaoufi/Desktop/volumes/mariadb
      o: bind

