FROM    debian:buster

RUN     apt-get update -y apt-get upgrade -y
RUN 	apt-get install -y php7.3 \ 
        php7.3-fpm php7.3-mysql mariadb-client \
        nginx curl
RUN     curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN     chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY    

EXPOSE  9000

ENTRYPOINT ["sh", "script.sh"]

CMD ["php-fpm7.3", "-R", "-F"]